# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Enclave settings:
# Debug=1
# NumHeapPages=1024
# NumStackPages=1024
# NumTCS=1
# ProductID=1
# SecurityVersion=1
Debug=1
# NumHeapPages=2026531
# NumStackPages=2026531
# NumHeapPages=32768
# NumStackPages=32768
# Together there are 8041856 / 4096 = 23936 pages
NumHeapPages=262144
NumStackPages=262144
NumTCS=1
ProductID=1
SecurityVersion=1
