// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <stdio.h>

// Include the trusted ecledger header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the ecledger.edl file.
#include "ecledger_t.h"

// custom types + lib for signing with secp256k1 curve
#include "common.h"
#include "data_types.h"
#include "ecl/ecl.h"
#include "sealing/sealing.h"
#include "signing-PB/signing.h"

// eEVM imports
#include "aleth-mp3/database/OverlayDB.h"
#include "aleth-mp3/database/MemoryDB.h"
#include "aleth-mp3/database/SecureTrieDB.h"
#include "eEVM/util.h"

EvmState_T _evm_state;
bool _evm_initialized = false;

Sealing _sealer;
ECLedger _ecl;

// TODO: this is just temp function: drop it later
void ecall_enclave_ecledger() {
    // fprintf(stdout, "[ENCLAVE]: Hello world from the enclave\n");
    std::cout << "[ENCLAVE]: Hello world from the enclave" << std::endl;

    // Call back into the host
    oe_result_t result = ocall_host_ecledger();
    if (result != OE_OK) {
        fprintf(stderr, "[ENCLAVE]: Call to ocall_host_ecledger failed: result=%u (%s)\n", result, oe_result_str(result));
    }
    ECLedger l = ECLedger();
    l.execute_hello_world();
    l.execute_sum_a_b(2, 3);


    // some tmp experiments with MP3 and DB
    auto mem_db = std::unique_ptr<dev::db::DatabaseFace>(new dev::db::MemoryDB());
    dev::OverlayDB * m_db = new dev::OverlayDB(std::move(mem_db));
    auto t = new dev::SecureTrieDB<dev::h256, dev::OverlayDB>(m_db);
    assert(t->isNull());

    t->init();

    assert(!t->isNull());
    assert(t->isEmpty());

    string inp4hash("some input text 4 hash");
    eevm::KeccakHash tx_hash = eevm::keccak_256(inp4hash);

    TRACE_ENCLAVE("1");
    auto hash = dev::h256(tx_hash.data(), dev::h256::ConstructFromPointer);
    TRACE_ENCLAVE("2");
    t->insert(hash, inp4hash);
    TRACE_ENCLAVE("3");
    assert(t->at(hash) == inp4hash);
    TRACE_ENCLAVE("4");
    t->remove(hash);
    TRACE_ENCLAVE("5");
    assert(t->isEmpty());
}

/*
* This function is called only once - when sealed file does not exist.
* The initialization of SK and PK under the signature scheme of the blockchain is performed here.
*/
int ecall_initialize_evm(secp256k1_pubkey* enc_pk, size_t enc_pk_size) {
    oe_result_t ocall_status, sealing_status;
    int ocall_ret, lib_ret;

    //check whether sealed state does not exist; if yes, then just init from it
    ocall_status = ocall_does_sealed_state_exist(&ocall_ret);
    if (ocall_status != OE_OK) {
        return ERR_STAT_FILE_INIT;
    }

    if (!ocall_ret) {
        // sealed state file does not exist, so create it

        EvmState_T* evm_state_unsealed = (EvmState_T*)malloc(sizeof(EvmState_T));
        memset(evm_state_unsealed, 0, sizeof(EvmState_T));

        // generate EVM key under sig. scheme of PB and store it to evm state struct
        if (0 != generate_keypair_PB(&evm_state_unsealed->sec.keypair)) {
            free(evm_state_unsealed);
            return ERR_KEYPAIR_GEN_FAILED;
        }
        evm_state_unsealed->pub.diskInits = 0;

        // store EVM state in enclave memory
        memcpy(&_evm_state, evm_state_unsealed, sizeof(EvmState_T));  // TODO: later do deep copy of err TXs

        // seal evm state object
        const size_t data_size = sizeof(EvmState_T);
        sealed_data_t* sealed_data = NULL;
        size_t sealed_data_size = 0;
        lib_ret = _sealer.seal_data(POLICY_UNIQUE, (const unsigned char*)&STATE_SEAL_MSG, STATE_SEAL_MSG_LEN,
            (const unsigned char*)evm_state_unsealed, data_size,
            &sealed_data, &sealed_data_size);
        if (OE_OK != lib_ret) {
            TRACE_ENCLAVE("sealing was not successfull, %d", lib_ret);
            return ERR_FAIL_SEAL_STATE;
        }

        TRACE_ENCLAVE("sizeof(EvmState_T) is %ld", data_size);
        TRACE_ENCLAVE("sizeof(sealed_data_t) is %ld", sizeof(sealed_data_t));
        TRACE_ENCLAVE("size of all sealed data that are written to HDD is %ld", sealed_data_size);

        // save sealed evm state to file, through OCALL
        ocall_status = ocall_save_evm_state(&ocall_ret, (const uint8_t*)sealed_data, sealed_data_size);
        free(sealed_data);
        if (RET_SUCCESS != ocall_ret || ocall_status != OE_OK) {
            TRACE_ENCLAVE("sealed data were not saved on disk, %s", oe_result_str(ocall_status));
            return ERR_CANNOT_SAVE_EVM_STATE;
        }
        _evm_initialized = true;
        (*enc_pk) = _evm_state.sec.keypair.PK_PB;
        return RET_SUCCESS_INIT_NEW_STATE;
    } else {
        // EVM state file exists, so initialize from it
        size_t tmp_sealed_data_size = sizeof(sealed_data_t) + sizeof(EvmState_T) + KEY_INFO_SIZE + MAX_PADDING;  // the last X Bytes are for keyinfo, TODO: check the precise size of key info
        uint8_t* sealed_data = (uint8_t*)malloc(tmp_sealed_data_size);
        ocall_status = ocall_load_evm_state(&ocall_ret, sealed_data, tmp_sealed_data_size);
        if (RET_SUCCESS != ocall_ret || OE_OK != ocall_status) {
            free(sealed_data);
            TRACE_ENCLAVE("ocall_load_evm_state failed, %s", oe_result_str(ocall_status));
            return ERR_CANNOT_LOAD_SEALED_STATE;
        }

        sealed_data_t* hdr = (sealed_data_t*)sealed_data;

        size_t sealed_data_size = hdr->encrypted_data_len;
        size_t data_size = hdr->original_data_size;
        unsigned char* data = NULL;

        lib_ret = _sealer.unseal_data((sealed_data_t*)sealed_data, sealed_data_size, &data, &data_size);
        if (OE_OK != lib_ret) {
            TRACE_ENCLAVE("unseal_data failed, %d", lib_ret);
            return ERR_LOAD_EVM_STATE;
        }

        EvmState_T* st = (EvmState_T*)data;

        st->pub.diskInits++;
        memcpy(&_evm_state, data, sizeof(EvmState_T));  // TODO: later do deep copy of err TXs
        _evm_initialized = true;

        free(sealed_data);
        free(data);

        (*enc_pk) = _evm_state.sec.keypair.PK_PB;
        return RET_SUCCESS_INIT_LOADED_STATE;
    }
}

int ecall_sync_evm_sealed_state_to_disk(void) {
    int ocall_ret;

    // seal internal EVM state object which is held in memory
    size_t data_size = sizeof(EvmState_T);
    sealed_data_t* sealed_data = NULL;
    size_t sealed_data_size = 0;
    int lib_ret = _sealer.seal_data(POLICY_UNIQUE, (unsigned char*)&STATE_SEAL_MSG, STATE_SEAL_MSG_LEN,
        (unsigned char*)&_evm_state, data_size,
        &sealed_data, &sealed_data_size);
    if (OE_OK != lib_ret) {
        TRACE_ENCLAVE("sealing was not successfull, %d", lib_ret);
        return ERR_FAIL_SEAL_STATE;
    }

    // save sealed evm state to file, through OCALL
    auto ocall_status = ocall_save_evm_state(&ocall_ret, (const uint8_t*)sealed_data, sealed_data_size);
    free(sealed_data);
    if (RET_SUCCESS != ocall_ret || OE_OK != ocall_status) {
        TRACE_ENCLAVE("sealed data were not saved on disk, %s", oe_result_str(ocall_status));
        return ERR_CANNOT_SAVE_EVM_STATE;
    }
    return 0;
}

int ecall_read_pub_state(PublicSealedData_T* pub_evm_state, size_t pub_state_size) {
    (*pub_evm_state) = _evm_state.pub;
    return 0;
}

int ecall_run_single_tx_simplestate(PersistantTxProxy_T* tx, size_t tx_size, const uint8_t* code, size_t code_size) {
    return _ecl.execute_tx(tx, code, code_size);
}
