// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <stdio.h>

// Include the trusted aqledger header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the aqledger.edl file.
#include "aqledger_t.h"

// custom types + lib for signing with secp256k1 curve
#include "common.h"
#include "data_types.h"
#include "ledger/aq_ledger.h"
#include "merkle-tree.h"
#include "sealing/sealing.h"
#include "signing.h"
// #include "stacktrace.h"


// eEVM imports
#include "aleth-mp3/database/MemoryDB.h"
#include "aleth-mp3/database/OverlayDB.h"
#include "aleth-mp3/database/SecureTrieDB.h"
#include "eEVM/normal/normalGlobalState.h"
#include "eEVM/util.h"

EvmState_T m_evm_state;
bool _evm_initialized = false;

Sealing m_sealer;
AQLedger m_ledger;
eevm::NormalGlobalState *m_gs = NULL;  // the partial global state of the ledger (maintained in memory of enclave)


///////////////////// AUX //////////////////

int generate_keypair_PB(KeyPairPB_T* keypair)
{
    TRACE_ENCLAVE("1");
    // 1) compute SK of PB by trusted random number generation
    if (OE_OK != oe_random(&(keypair->SK_PB), ECC_SK_SIZE)) {
        return ERR_RAND_FAILED;
    }
    TRACE_ENCLAVE("2");
    // 2) compute PK of PB from SK
    if (RET_SUCCESS != m_ledger.ecc.compute_PK_from_SK(keypair)) {
        return ERR_KEYPAIR_GEN_FAILED;
    }
    TRACE_ENCLAVE("3");
    return RET_SUCCESS;
}

///////////////////////////////////////////

// TODO: this is just temp function: drop it later
void ecall_enclave_aqledger()
{
    try {
        print_enc_sep(EncExec::START);
        // fprintf(stdout, "[ENCLAVE]: Hello world from the enclave\n");
        std::cout << "[ENCLAVE]: Hello world from the enclave" << std::endl;

        // Call back into the host
        oe_result_t result = ocall_host_aqledger();
        if (result != OE_OK) {
            fprintf(stderr, "[ENCLAVE]: Call to ocall_host_aqledger failed: result=%u (%s)\n", result, oe_result_str(result));
        }
        AQLedger l = AQLedger();
        l.execute_hello_world();
        l.execute_sum_a_b(2, 3);


        // some tmp experiments with MP3 and DB
        auto mem_db = std::unique_ptr<dev::db::DatabaseFace>(new dev::db::MemoryDB());
        dev::OverlayDB* m_db = new dev::OverlayDB(std::move(mem_db));
        auto t = new dev::SecureTrieDB<dev::h256, dev::OverlayDB>(m_db);
        assert(t->isNull());

        t->init();

        assert(!t->isNull());
        assert(t->isEmpty());

        string inp4hash("some input text 4 hash");
        eevm::KeccakHash tx_hash = eevm::keccak_256(inp4hash);

        TRACE_ENCLAVE("1");
        auto hash = dev::h256(tx_hash.data(), dev::h256::ConstructFromPointer);
        TRACE_ENCLAVE("2");
        t->insert(hash, inp4hash);
        TRACE_ENCLAVE("3");
        assert(t->at(hash) == inp4hash);
        TRACE_ENCLAVE("4");
        t->remove(hash);
        TRACE_ENCLAVE("5");
        assert(t->isEmpty());

        print_enc_sep(EncExec::END);
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
    }
}

/*
* This function is called only once - when sealed file does not exist.
* The initialization of SK and PK under the signature scheme of the blockchain is performed here.
* The root hash of empty MP3 is stored here
*/
int ecall_initialize_evm(secp256k1_pubkey* enc_pk, size_t enc_pk_size)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("Initializing EVM enclave.");

        if(MODE::FullStateMaintained == DEFAULT_MODE){
            m_gs = new eevm::NormalGlobalState(); // create MP3 object - TODO: if sealed file exists, initiate it from it (MP3 DB should contain only some cached data).
        }        

        oe_result_t ocall_status;
        int ocall_ret, lib_ret;

        //check whether sealed state does not exist; if yes, then just init from it
        ocall_status = ocall_does_sealed_state_exist(&ocall_ret);
        if (ocall_status != OE_OK) {
            return ERR_STAT_FILE_INIT;
        }

        if (!ocall_ret) {
            // sealed state file of E does not exist, so create it

            EvmState_T* evm_state_unsealed = (EvmState_T*)malloc(sizeof(EvmState_T));
            memset(evm_state_unsealed, 0, sizeof(EvmState_T));

            // generate E's key under sig. scheme of PB and store it to evm state struct
            if (0 != generate_keypair_PB(&evm_state_unsealed->sec.keypair)) {
                free(evm_state_unsealed);
                return ERR_KEYPAIR_GEN_FAILED;
            }
            evm_state_unsealed->pub.diskInits = 0;
            uint8_t gsRoot[HASH_SIZE];
            eevm::to_big_endian(dev::sha3(dev::RLPNull), gsRoot);
            memcpy(evm_state_unsealed->pub.globStRoot, gsRoot, HASH_SIZE);  // compute root of empty MP3 global state

            // store E's state in enclave memory
            memcpy(&m_evm_state, evm_state_unsealed, sizeof(EvmState_T));  // TODO: later do deep copy of err TXs

            // seal E state object
            const size_t data_size = sizeof(EvmState_T);
            sealed_data_t* sealed_data = NULL;
            size_t sealed_data_size = 0;
            lib_ret = m_sealer.seal_data(POLICY_UNIQUE, (const unsigned char*)&STATE_SEAL_MSG, STATE_SEAL_MSG_LEN,
                                        (const unsigned char*)evm_state_unsealed, data_size,
                                        &sealed_data, &sealed_data_size);
            if (OE_OK != lib_ret) {
                TRACE_ENCLAVE("sealing was not successfull, %d", lib_ret);
                return ERR_FAIL_SEAL_STATE;
            }

            TRACE_ENCLAVE("sizeof(EvmState_T) is %ld", data_size);
            TRACE_ENCLAVE("sizeof(sealed_data_t) is %ld", sizeof(sealed_data_t));
            TRACE_ENCLAVE("size of all sealed data that are written to HDD is %ld", sealed_data_size);

            // save sealed evm state to file, through OCALL
            ocall_status = ocall_save_evm_state(&ocall_ret, (const uint8_t*)sealed_data, sealed_data_size);
            free(sealed_data);
            if (RET_SUCCESS != ocall_ret || ocall_status != OE_OK) {
                TRACE_ENCLAVE("sealed data were not saved on disk, %s", oe_result_str(ocall_status));
                return ERR_CANNOT_SAVE_EVM_STATE;
            }
            _evm_initialized = true;  // update enclave memory
            (*enc_pk) = m_evm_state.sec.keypair.PK_PB;

            print_enc_sep(EncExec::END);
            return RET_SUCCESS_INIT_NEW_STATE;
        } else {
            // EVM state file exists, so initialize from it
            size_t tmp_sealed_data_size = sizeof(sealed_data_t) + sizeof(EvmState_T) + KEY_INFO_SIZE + MAX_PADDING;  // the last X Bytes are for keyinfo, TODO: check the precise size of key info
            uint8_t* sealed_data = (uint8_t*)malloc(tmp_sealed_data_size);
            ocall_status = ocall_load_evm_state(&ocall_ret, sealed_data, tmp_sealed_data_size);
            if (RET_SUCCESS != ocall_ret || OE_OK != ocall_status) {
                free(sealed_data);
                TRACE_ENCLAVE("ocall_load_evm_state failed, %s", oe_result_str(ocall_status));
                return ERR_CANNOT_LOAD_SEALED_STATE;
            }

            sealed_data_t* hdr = (sealed_data_t*)sealed_data;

            size_t sealed_data_size = hdr->encrypted_data_len;
            size_t data_size = hdr->original_data_size;
            unsigned char* data = NULL;

            lib_ret = m_sealer.unseal_data((sealed_data_t*)sealed_data, sealed_data_size, &data, &data_size);
            if (OE_OK != lib_ret) {
                TRACE_ENCLAVE("unseal_data failed, %d", lib_ret);
                return ERR_LOAD_EVM_STATE;
            }

            EvmState_T* st = (EvmState_T*)data;

            st->pub.diskInits++;
            memcpy(&m_evm_state, data, sizeof(EvmState_T));  // TODO: later do deep copy of err TXs
            _evm_initialized = true;

            free(sealed_data);
            free(data);

            (*enc_pk) = m_evm_state.sec.keypair.PK_PB;
            print_enc_sep(EncExec::END);
            return RET_SUCCESS_INIT_LOADED_STATE;
        }
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}

int ecall_sync_evm_sealed_state_to_disk(void)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("syncing sealed state to disk.");

        int ocall_ret;

        // seal internal EVM state object which is held in memory
        size_t data_size = sizeof(EvmState_T);
        sealed_data_t* sealed_data = NULL;
        size_t sealed_data_size = 0;
        int lib_ret = m_sealer.seal_data(POLICY_UNIQUE, (unsigned char*)&STATE_SEAL_MSG, STATE_SEAL_MSG_LEN,
                                        (unsigned char*)&m_evm_state, data_size,
                                        &sealed_data, &sealed_data_size);
        if (OE_OK != lib_ret) {
            TRACE_ENCLAVE("sealing was not successfull, %d", lib_ret);
            return ERR_FAIL_SEAL_STATE;
        }

        // save sealed evm state to file, through OCALL
        auto ocall_status = ocall_save_evm_state(&ocall_ret, (const uint8_t*)sealed_data, sealed_data_size);
        free(sealed_data);
        if (RET_SUCCESS != ocall_ret || OE_OK != ocall_status) {
            TRACE_ENCLAVE("sealed data were not saved on disk, %s", oe_result_str(ocall_status));
            return ERR_CANNOT_SAVE_EVM_STATE;
        }
        print_enc_sep(EncExec::END);
        return 0;

    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}

int ecall_read_pub_state(PublicSealedData_T* pub_evm_state, size_t pub_state_size)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("reading public state.");
        (*pub_evm_state) = m_evm_state.pub;
        print_enc_sep(EncExec::END);
        return 0;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}

int ecall_read_memory_stats(StorageStatsMP3DB* evm_mem_stats, size_t evm_mem_stats_size)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("reading memory stats of MP3 DB in enclave.");
        if(NULL == m_gs){
            return ERR_NOT_FSMAINTAINED_MODE;            
        } 
                
        assert(sizeof(StorageStatsMP3DB) == sizeof(dev::StateCacheDB::StorageStatsMP3DB));
        (*evm_mem_stats) = *reinterpret_cast<StorageStatsMP3DB*>(&(m_gs->db()->m_stats));

        print_enc_sep(EncExec::END);
        return 0;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}

int ecall_purge_stale_mp3_entries (){
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("Purging stale entries in MP3 DB.");
        if(NULL == m_gs){
            return ERR_NOT_FSMAINTAINED_MODE;            
        } 
                
        m_gs->db()->purge();

        print_enc_sep(EncExec::END);
        return 0;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}

int ecall_set_operator_address(uint8_t* operator_PK, size_t pk_size)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("setting operator's address.");
        assert(pk_size == PK_SIZE_PB);
        uint256_t opAddr = eevm::from_big_endian(operator_PK, eevm::ADDR_ETH_SIZE_B);
        m_ledger.operAddr = opAddr;
        print_enc_sep(EncExec::END);
        return 0;

    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}


int ecall_run_single_tx_simplestate(PersistantTxProxy_T* tx, size_t tx_size, const uint8_t* code, size_t code_size)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("running TX with internal simplestate.");
        int ret = m_ledger.execute_tx_simplestate_internal(tx, code, code_size);
        print_enc_sep(EncExec::END);
        return ret;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}


int ecall_run_single_tx_mp3state_full(PersistantTxProxy_T* tx, size_t tx_size,
                                      const uint8_t* code, size_t code_size,
                                      const uint8_t* mp3_keys, size_t mp3_keys_size,  // from here below is MP3  global state
                                      const uint8_t* mp3_values, const size_t* mp3_values_sizes, size_t mp3_values_sizes_size,
                                      const uint8_t* storages, const size_t* storages_sizes, size_t storages_sizes_size)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("running TX with full MP3 copied.");

        // 1) reconstruct the global MP3 state from host passed data
        eevm::NormalGlobalState* gs;
        int ret = eevm::NormalGlobalState::construct_full_state(&gs,
                                                                mp3_keys, mp3_keys_size,
                                                                mp3_values, mp3_values_sizes, mp3_values_sizes_size,
                                                                storages, storages_sizes, storages_sizes_size);
        if (ret != RET_SUCCESS)
            return ERR_EVM_WRONG_FULL_STATE;

        // 2) verify a consistency of the reconstructed global state with the last known value stored in E
        // std::cerr << "gs->getAccounts().root() = " << (gs->getAccounts().root()) << "\n";
        // std::cerr << "m_evm_state.pub.globStRoot = " << eevm::to_hex_string(eevm::from_big_endian(m_evm_state.pub.globStRoot)) << "\n";
        if ((gs->getAccounts().root()) != eevm::from_big_endian(m_evm_state.pub.globStRoot)) {  // operator (h256) converts to underlying object
            TRACE_ENCLAVE("Passed global state IS NOT consistent with the last known one.");
            delete gs;
            return ERR_EVM_INCONSISTANT_STATE;
        }
        TRACE_ENCLAVE("Passed global state IS consistent with the one from E.");

        // 3) Execute TX in E (while updating the protected global state)
        ret = m_ledger.execute_tx_mp3state_full(gs, tx, code, code_size);

        // 4) update the current root hash of the global MP3 state in E
        memcpy(&m_evm_state.pub.globStRoot, gs->getAccounts().root().data(), HASH_SIZE);

        delete gs;  // clear global state allocated before
        print_enc_sep(EncExec::END);
        return ret;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}


int ecall_run_single_tx_mp3state_partial(PersistantTxProxy_T* tx, size_t tx_size,
                                         const uint8_t* code, size_t code_size,
                                         const uint8_t* gs_root_h, size_t root_size,
                                         const uint8_t* db_data, size_t db_data_size,
                                         const uint8_t* db_data_aux, size_t db_data_aux_size,
                                         const uint8_t* storages, const size_t* storages_sizes, size_t storages_sizes_size, const uint8_t* accnts_of_storages)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("executing TX with partial MP3 copied.");

        // 1) reconstruct the global MP3 state from host passed data
        eevm::NormalGlobalState* gs;
        int ret = eevm::NormalGlobalState::construct_partial_state(&gs, gs_root_h,
                                                                   db_data, db_data_size,
                                                                   db_data_aux, db_data_aux_size,
                                                                   storages, storages_sizes, storages_sizes_size, accnts_of_storages);
        if (ret != RET_SUCCESS)
            return ERR_EVM_WRONG_PARTIAL_STATE;

        // 2) verify a consistency of the reconstructed global state with the last known value stored in E
        if ((gs->getAccounts().root()) != eevm::from_big_endian(m_evm_state.pub.globStRoot)) {  // operator (h256) converts to underlying object
            TRACE_ENCLAVE("Passed global state IS NOT consistent with the last known one.");
            delete gs;
            return ERR_EVM_INCONSISTANT_STATE;
        }
        TRACE_ENCLAVE("Passed global state IS consistent with the one from E.");

        // 3) Execute TX in E (while updating the protected global state)
        ret = m_ledger.execute_tx_mp3state_full(gs, tx, code, code_size);

        // 4) update the current root hash of the global MP3 state in E
        memcpy(&m_evm_state.pub.globStRoot, gs->getAccounts().root().data(), HASH_SIZE);

        delete gs;  // clear global state allocated before
        print_enc_sep(EncExec::END);
        return ret;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        return ERR_EXCEPTION;
    }
}

/**
 * This function prcesses TXs in batches and thus creates the blocks.
 */
int ecall_run_many_txs_mp3state_partial(const uint8_t* txs, size_t txs_size,
                                        const uint8_t* codes, size_t codes_sum_size, const size_t* codes_sizes, size_t codes_sizes_size,
                                        const uint8_t* gs_root_h, size_t root_size, // from here below is partial MP3 DB
                                        const uint8_t* db_data, size_t db_data_size,
                                        const uint8_t* db_data_aux, size_t db_data_aux_size,
                                        const uint8_t* storages, const size_t* storages_sizes, size_t storages_sizes_size, const uint8_t* accnts_of_storages)
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("executing many TXs with partial MP3 copied.");

        // 1) reconstruct the global MP3 state from host passed data
        eevm::NormalGlobalState* gs;
        // TODO: we need caching of the partial state in the enclave up to some depth - so we can transfer / process lesser data by ecall
        int32_t ret = eevm::NormalGlobalState::construct_partial_state(&gs, gs_root_h,
                                                                       db_data, db_data_size,
                                                                       db_data_aux, db_data_aux_size,
                                                                       storages, storages_sizes, storages_sizes_size, accnts_of_storages);
        if (ret != RET_SUCCESS)
            return ERR_EVM_WRONG_PARTIAL_STATE;

        // 2) verify a consistency of the reconstructed global state with the last known value stored in E
        if ((gs->getAccounts().root()) != eevm::from_big_endian(m_evm_state.pub.globStRoot)) {  // operator parenthesis (h256) converts to underlying object
            TRACE_ENCLAVE("Passed global state IS NOT consistent with the last known one.");
            delete gs;
            return ERR_EVM_INCONSISTANT_STATE;
        }
        TRACE_ENCLAVE("Passed global state IS consistent with the one from E.");

        // 3) Execute TXs in E one by one (while updating the protected global state)
        size_t codes_offset = 0;
        MerkleTreeArray txs_hashes;
        MerkleTreeArray rcps_hashes;
        for (size_t i = 0; i < txs_size / sizeof(PersistantTxProxy_T); i++) {
            PersistantTxProxy_T* ptx = (PersistantTxProxy_T*)(txs + i * sizeof(PersistantTxProxy_T));
            ret = m_ledger.execute_tx_mp3state_full(gs, ptx, codes + codes_offset, codes_sizes[i], &txs_hashes);            
            if (ERR_EVM_SENDER_DOES_NOT_EXIST != ret) {  // some types of malformed txs do not append into log (and thus do not create receipts for them)                
                eevm::KeccakHash rcpHash = eevm::keccak_256(reinterpret_cast<const uint8_t*>(&ret), sizeof(int32_t));                
                rcps_hashes.add(rcpHash);                
            }
            codes_offset += codes_sizes[i];
        }
        assert(codes_offset == codes_sum_size);
        TRACE_ENCLAVE("5");


        // 4) Update the current root hash of the global MP3 state in E
        memcpy(&m_evm_state.pub.globStRoot, gs->getAccounts().root().data(), HASH_SIZE);

        // 5) Compute and store the Merkle root of TXs
        dev::h256 txsRoot = txs_hashes.computeRoot();
        memcpy(&m_evm_state.pub.txsRoot, txsRoot.begin(), HASH_SIZE);

        // 6) Compute and store Merkle root of receipts (i.e., return codes)
        dev::h256 rcpsRoot = rcps_hashes.computeRoot();
        memcpy(&m_evm_state.pub.rcpsRoot, rcpsRoot.begin(), HASH_SIZE);

        // 7) Increment ID of the current block
        m_evm_state.pub.idCurrent++;


        delete gs;  // clear global state allocated before
        print_enc_sep(EncExec::END);
        return ret;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        // auto s = backtrace();
        // std::cerr << "backtrace(): \n" << s << '\n';
        return ERR_EXCEPTION;
    }
}

/**
 * This function prcesses TXs in batches and thus creates the blocks.
 * The state of EVM is fully stored and maintained in the enclave.
 */
int ecall_run_many_txs_maintained_full_mp3state(const uint8_t* txs, size_t txs_size, 
                    const uint8_t* codes, size_t codes_sum_size, 
                    const size_t* codes_sizes, size_t codes_sizes_size)                                        
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("executing many TXs with full MP3 maintained in enclave.");

        int32_t ret;

        // 1) Execute TXs in E one by one (while updating the protected global state)
        size_t codes_offset = 0;
        MerkleTreeArray txs_hashes;
        MerkleTreeArray rcps_hashes;
        for (size_t i = 0; i < txs_size / sizeof(PersistantTxProxy_T); i++) {
            PersistantTxProxy_T* ptx = (PersistantTxProxy_T*)(txs + i * sizeof(PersistantTxProxy_T));
            ret = m_ledger.execute_tx_mp3state_full(m_gs, ptx, codes + codes_offset, codes_sizes[i], &txs_hashes);            
            if (ERR_EVM_SENDER_DOES_NOT_EXIST != ret) {  // some types of malformed txs do not append into log (and thus do not create receipts for them)                
                eevm::KeccakHash rcpHash = eevm::keccak_256(reinterpret_cast<const uint8_t*>(&ret), sizeof(int32_t));                
                rcps_hashes.add(rcpHash);                
            }            
            codes_offset += codes_sizes[i]; 
            // m_gs->db()->purge(); // this is less efficient than doing it after batch
        }
        assert(codes_offset == codes_sum_size);        

        // 2) Update the current root hash of the global MP3 state in E
        memcpy(&m_evm_state.pub.globStRoot, m_gs->getAccounts().root().data(), HASH_SIZE);

        // 3) Compute and store the Merkle root of TXs
        dev::h256 txsRoot = txs_hashes.computeRoot();
        memcpy(&m_evm_state.pub.txsRoot, txsRoot.begin(), HASH_SIZE);

        // 4) Compute and store Merkle root of receipts (i.e., return codes)
        dev::h256 rcpsRoot = rcps_hashes.computeRoot();
        memcpy(&m_evm_state.pub.rcpsRoot, rcpsRoot.begin(), HASH_SIZE);

        // 5) Increment ID of the current block
        m_evm_state.pub.idCurrent++;

        // 6) Clean up unused entries in MP3 db - should be done manually from host
        m_gs->db()->purge(); 
        
        print_enc_sep(EncExec::END);
        return ret;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        // auto s = backtrace();
        // std::cerr << "backtrace(): \n" << s << '\n';
        return ERR_EXCEPTION;
    }
}

/**
 * This function prcesses TXs in batches and thus creates the blocks.
 * The state of EVM is fully stored and maintained in the enclave.
 * eEVM is executed only in enclave, not in host, therefore this function 
 * provides host with the list of updated and modified AS objects, which are 
 * stored to untrusted memory 'updated_and_new_accnts' and 'updated_and_new_strgs'
 */
int ecall_run_many_txs_maintained_full_mp3state_singleExec(const uint8_t * txs, size_t txs_size, uint8_t * output_results,
                    const uint8_t* codes, size_t codes_sum_size, 
                    const size_t* codes_sizes, size_t codes_sizes_size,
                    uint8_t * updated_and_new_accnts, size_t * accnts_sizes, size_t * accnts_sizes_size, size_t MAX_SIZE_accnts, size_t MAX_SIZE_accnts_sizes, 
                    uint8_t * updated_and_new_strgs, size_t * strgs_sizes, size_t * strgs_sizes_size, size_t MAX_SIZE_strgs, size_t MAX_SIZE_strgs_sizes)                                        
{
    try {
        print_enc_sep(EncExec::START);
        TRACE_ENCLAVE("executing many TXs with full MP3 maintained in enclave.");

        int32_t ret;        
        size_t numberOfTxs = txs_size / sizeof(PersistantTxProxy_T);

        // 0) perform memory location check - must be STRICTLY outside of the enlclave (i.e., not overlapping with E)
        if(!oe_is_outside_enclave(output_results, 32 * numberOfTxs)) // we know this size beforehand: 32B is the size per one output
            return ERR_POINTER_NOT_OUTSIDE_OF_ENC;
        if(!oe_is_outside_enclave(updated_and_new_accnts, MAX_SIZE_accnts)) // check the max size allocated in host
            return ERR_POINTER_NOT_OUTSIDE_OF_ENC;
        if(!oe_is_outside_enclave(accnts_sizes, MAX_SIZE_accnts_sizes)) // check the max size allocated in host
            return ERR_POINTER_NOT_OUTSIDE_OF_ENC;
        if(!oe_is_outside_enclave(updated_and_new_strgs, MAX_SIZE_strgs)) // check the max size allocated in host
            return ERR_POINTER_NOT_OUTSIDE_OF_ENC;
        if(!oe_is_outside_enclave(strgs_sizes, MAX_SIZE_strgs_sizes)) // check the max size allocated in host
            return ERR_POINTER_NOT_OUTSIDE_OF_ENC;
        
        // 1) Start logging of new/updated addresses - after execution of EVM, process the set of addresses and fetch final ASes
        std::unordered_set<eevm::Address> newAndUpdatedAddrs;
        m_gs->startASLogging(&newAndUpdatedAddrs); // start logging of account state into protected local set
        
        // 2) Execute TXs in E one by one (while updating the protected global state)
        size_t codes_offset = 0;
        MerkleTreeArray txs_hashes;
        MerkleTreeArray rcps_hashes;
        for (size_t i = 0; i < numberOfTxs; i++) {
            PersistantTxProxy_T* ptx = (PersistantTxProxy_T*)(txs + i * sizeof(PersistantTxProxy_T));
            ret = m_ledger.execute_tx_mp3state_full(m_gs, ptx, codes + codes_offset, codes_sizes[i], &txs_hashes, &output_results[i * 32]);            
            if (ERR_EVM_SENDER_DOES_NOT_EXIST != ret) {  // some types of malformed txs do not append into log (and thus do not create receipts for them)                
                eevm::KeccakHash rcpHash = eevm::keccak_256(reinterpret_cast<const uint8_t*>(&ret), sizeof(int32_t));                
                rcps_hashes.add(rcpHash);                
            }            
            codes_offset += codes_sizes[i]; 
            // m_gs->db()->purge(); // this is less efficient than doing it after batch
        }
        assert(codes_offset == codes_sum_size);           
        m_gs->finishASLogging();  

        // check size of sizes buffers and reallocate by OCALL if needed
        if(newAndUpdatedAddrs.size() > MAX_SIZE_accnts_sizes) 
            throw std::logic_error("Not implemented - host buffer should be reallocated in OCALL (oe_host_realloc), while returing a new data pointer (with orig data in location it points to).");        

        // 2) serialize logged addresses into [user_check] buffers of host memory                       
        size_t i = 0, sum_size_strgs = 0, sum_size_accnts = 0;         
        for(auto& addr: newAndUpdatedAddrs){
            auto newAs = m_gs->get(addr);            
            
            // a) copy storage object to the host buffer 
            if(newAs.st.sizeB() + sum_size_strgs > MAX_SIZE_strgs) 
                throw std::logic_error("Not implemented - host buffer should be reallocated in OCALL (oe_host_realloc), while returing a new data pointer (with orig data in location it points to).");            
            size_t s = newAs.st.toBytes(updated_and_new_strgs + sum_size_strgs);
            *(strgs_sizes + i) = s;
            sum_size_strgs += s;            

            // b) copy account object to the host buffer (it contains address)
            s = newAs.acc.sizeB();
            if(s + sum_size_accnts > MAX_SIZE_accnts) 
                throw std::logic_error("Not implemented - host buffer should be reallocated in OCALL (oe_host_realloc), while returing a new data pointer (with orig data in location it points to).");
            newAs.acc.toBytes(updated_and_new_accnts + sum_size_accnts); 
            *(accnts_sizes + i) = s;
            sum_size_accnts += s;            
        
            i++;
        }                
        *strgs_sizes_size = i;
        *accnts_sizes_size = i;        

        // 2) Update the current root hash of the global MP3 state in E
        memcpy(&m_evm_state.pub.globStRoot, m_gs->getAccounts().root().data(), HASH_SIZE);

        // 3) Compute and store the Merkle root of TXs
        dev::h256 txsRoot = txs_hashes.computeRoot();
        memcpy(&m_evm_state.pub.txsRoot, txsRoot.begin(), HASH_SIZE);

        // 4) Compute and store Merkle root of receipts (i.e., return codes)
        dev::h256 rcpsRoot = rcps_hashes.computeRoot();
        memcpy(&m_evm_state.pub.rcpsRoot, rcpsRoot.begin(), HASH_SIZE);

        // 5) Increment ID of the current block
        m_evm_state.pub.idCurrent++;

        // 6) Clean up unused entries in MP3 db (it is fastest when doing after each block)
        m_gs->db()->purge(); 
        
        print_enc_sep(EncExec::END);
        return ret;
    } catch (const std::exception& e) {
        std::cerr << e.what() << '\n';
        // auto s = backtrace();
        // std::cerr << "backtrace(): \n" << s << '\n';
        return ERR_EXCEPTION;
    }
}
