#pragma once

#include <vector>

// includes from eEVM
#include "eEVM/address.h"
#include "eEVM/bigint.h"
#include "eEVM/transaction.h"

#include "data_types.h"
#include "ecl-host.h"
#include "ecledger_u.h"

#include "signing.h"

#define FILE_OPERATOR_KEYS "./data/operator-keys.txt"
#define MAX_CMD_LEN 256

// default numbers of unprocessed TXs and processed blocks required to flush into VM enclave / PB
#define NUM_TXS_FLUSH_VM 10
#define NUM_BLKS_FLUSH_PB 50

// default flushing timeouts in seconds
#define TIMEOUT_FLUSH_VM 20
#define TIMEOUT_FLUSH_PB 40

namespace ecl
{
    struct Header {
        uint256_t id;         // increment-only counter
        uint256_t txs_root;   // Merkle root
        uint256_t rcps_root;  // Merkle root
        uint256_t st_root;    // Merkle-Patricia root
    };

    struct Block {
        Header hdr;
        std::vector<eevm::PersistantTransaction> txs;   // transactions
        std::vector<eevm::PersistantTransaction> rcps;  // recipes associated with transactions
    };

    struct FlushingLimits {
        uint num_txs_VM = NUM_TXS_FLUSH_VM;    // the number of uprocessed txs for flushing to VM enclave
        uint num_blks_PB = NUM_BLKS_FLUSH_PB;  // the number of processed blocks for flushing to PB

        uint timeout_VM = TIMEOUT_FLUSH_VM;  // timeout for flushing to VM enclave,
        uint timeout_PB = TIMEOUT_FLUSH_PB;  // timeout for flushing to PB,
    };

    class Operator {
    public:
        ECC m_ecc;                                                     // ECC signing wrapper
        ECLedger m_ecl;                                                // ECL ledger instance
        std::vector<ContrDefinition> m_definitions;                    // Cache of parsed contract definition files
        std::unordered_map<eevm::Address, OperAccount> m_accounts;  // all testing accounts generated by O

        uint8_t PK_E_TEE[ECC_SK_SIZE];
        secp256k1_pubkey PK_E_PB;   // public key (i.e., unsigned char [64])
        secp256k1_pubkey PK_O;      // PK of operator (under Sigma_PB)
        uint8_t SK_O[ECC_SK_SIZE];  // SK of operator (under Sigma_PB)

        std::vector<eevm::PersistantTransaction> txs_unprocessed;  // cache of unprocessed TXs,
        std::vector<Block> blks_processed;                         // cache of processed blocks, not synced with PB yet

        std::vector<eevm::PersistantTransaction> cens_txs;  // cache of posted cens. TXs to smart contract

        std::vector<Block> ledger_stable;  // data of Ledger that were synced with PB,

        uint256_t LRoot_PB;   // the last root of Ledger flushed to PB,
        uint256_t LRoot_cur;  // the current root of (L U blks_processed) not flushed to PB

        uint t_vm;                  // time of the last flush to VM enclave
        uint t_pb;                  // time of the last flush to PB
        FlushingLimits flush_lims;  // the flushing limits


        Operator(secp256k1_pubkey* _enc_PK);
        ~Operator() {}

        inline eevm::Address& getOperAddr() { return m_ecl.operAddr; }
        inline eevm::SimpleAccountState getAccount(eevm::Address& addr) { return m_ecl.m_gs.get(addr); }

        void sendMyPKtoEnclave(oe_enclave_t* enclave);
        void operatorLoop(oe_enclave_t* enclave);
        void _createMyAccntState(oe_enclave_t* enclave);
        ContrDefinition _parseDefinitionFile(const std::string& contract_path);

    private:
        int persistMyKeys();
        bool existsMyKeyFile();
        int loadMyKeysFromFile();

        void printEvmState(PublicSealedData_T& es);
        void _printGlobalState(unsigned max);

        void _createNRandomAccounts(unsigned N, unsigned initBalance, oe_enclave_t* enclave);

        int _dispatchTX(oe_enclave_t* enclave, eevm::PersistantTransaction* tx);
    };

}  // namespace ecl
